### ISSUE TITLE
dlsym not able to find the symbol (VSOMEIP_CFG_RUNTIME)

### ISSUE THREAD

**Issue by uj864** [bonewell/franca-capi-someip-sample#2]
I am building the vsomeip apps for qnx platform, I have used the implementation from branch release/qnx660/2.5.2. dlsym in vsomeip-master/implementation/utility/src/utility.cpp points to null pointer, nm libvsomeip-cfg.so.2 does not show any symbol for VSOMEIP_CFG_RUNTIME. Can you help me understand what could be the problem.

**Comment by bonewell** [comment]
I'm not specialist of vsomeip. I just did minimal changes in vsomeip to build for QNX. It works for my sample. It is better to ask authors of vsomeip project.
